# Generated by Django 4.1.2 on 2022-10-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_advocate_profile_pic_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='advocate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.advocate'),
            preserve_default=False,
        ),
    ]
