# Generated by Django 4.1.2 on 2022-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
